[package]
name = "weather_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0", features=["derive"]}
reqwest = {version = "0.11", features=["blocking", "json"]}
serde_json = "1.0"
colored ="2.0"
dotenv = "0.15.0"
